#Make by Hieus
#Github : https://github.com/Hiesu19


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube

import os

os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = ".\\platform\\"

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(798, 600)
		font = QtGui.QFont()
		font.setPointSize(12)
		MainWindow.setFont(font)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("youtube.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(10, 10, 221, 31))
		font = QtGui.QFont()
		font.setPointSize(18)
		font.setBold(False)
		font.setWeight(50)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(230, 10, 47, 13))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_2.setFont(font)
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(10, 80, 111, 31))
		font = QtGui.QFont()
		font.setPointSize(16)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.label_4 = QtWidgets.QLabel(self.centralwidget)
		self.label_4.setGeometry(QtCore.QRect(530, 0, 61, 20))
		font = QtGui.QFont()
		font.setPointSize(6)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.get_link = QtWidgets.QLineEdit(self.centralwidget)
		self.get_link.setGeometry(QtCore.QRect(110, 80, 351, 31))
		self.get_link.setObjectName("get_link")
		self.check_box = QtWidgets.QPushButton(self.centralwidget)
		self.check_box.setGeometry(QtCore.QRect(470, 90, 75, 23))
		self.check_box.setObjectName("check_box")
		self.label_5 = QtWidgets.QLabel(self.centralwidget)
		self.label_5.setGeometry(QtCore.QRect(80, 330, 71, 31))
		font = QtGui.QFont()
		font.setPointSize(15)
		font.setBold(True)
		font.setItalic(False)
		font.setUnderline(True)
		font.setWeight(75)
		font.setStrikeOut(False)
		self.label_5.setFont(font)
		self.label_5.setObjectName("label_5")
		self.label_6 = QtWidgets.QLabel(self.centralwidget)
		self.label_6.setGeometry(QtCore.QRect(10, 140, 47, 13))
		self.label_6.setObjectName("label_6")
		self.download_now = QtWidgets.QPushButton(self.centralwidget)
		self.download_now.setGeometry(QtCore.QRect(300, 420, 261, 51))
		font = QtGui.QFont()
		font.setPointSize(16)
		self.download_now.setFont(font)
		self.download_now.setObjectName("download_now")
		self.title_box = QtWidgets.QLineEdit(self.centralwidget)
		self.title_box.setGeometry(QtCore.QRect(70, 130, 411, 21))
		self.title_box.setReadOnly(True)
		self.title_box.setObjectName("title_box")
		self.comboBox = QtWidgets.QComboBox(self.centralwidget)
		self.comboBox.setGeometry(QtCore.QRect(60, 370, 111, 22))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.comboBox.setFont(font)
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.label_7 = QtWidgets.QLabel(self.centralwidget)
		self.label_7.setGeometry(QtCore.QRect(330, 330, 81, 20))
		font = QtGui.QFont()
		font.setPointSize(15)
		font.setBold(True)
		font.setUnderline(True)
		font.setWeight(75)
		self.label_7.setFont(font)
		self.label_7.setObjectName("label_7")
		self.save = QtWidgets.QLineEdit(self.centralwidget)
		self.save.setGeometry(QtCore.QRect(300, 370, 241, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.save.setFont(font)
		self.save.setText("")
		self.save.setObjectName("save")
		self.view_box = QtWidgets.QLineEdit(self.centralwidget)
		self.view_box.setGeometry(QtCore.QRect(40, 200, 121, 20))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.view_box.setFont(font)
		self.view_box.setReadOnly(True)
		self.view_box.setObjectName("view_box")
		self.label_8 = QtWidgets.QLabel(self.centralwidget)
		self.label_8.setGeometry(QtCore.QRect(80, 170, 47, 13))
		self.label_8.setObjectName("label_8")
		self.label_9 = QtWidgets.QLabel(self.centralwidget)
		self.label_9.setGeometry(QtCore.QRect(330, 170, 141, 16))
		self.label_9.setObjectName("label_9")
		self.thumbnail_box = QtWidgets.QLineEdit(self.centralwidget)
		self.thumbnail_box.setGeometry(QtCore.QRect(240, 200, 321, 20))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.thumbnail_box.setFont(font)
		self.thumbnail_box.setReadOnly(True)
		self.thumbnail_box.setObjectName("thumbnail_box")
		self.label_10 = QtWidgets.QLabel(self.centralwidget)
		self.label_10.setGeometry(QtCore.QRect(30, 510, 521, 61))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.label_10.setFont(font)
		self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.label_10.setFrameShape(QtWidgets.QFrame.Box)
		self.label_10.setText("")
		self.label_10.setScaledContents(False)
		self.label_10.setObjectName("label_10")
		self.label_11 = QtWidgets.QLabel(self.centralwidget)
		self.label_11.setGeometry(QtCore.QRect(420, 340, 41, 20))
		font = QtGui.QFont()
		font.setPointSize(7)
		self.label_11.setFont(font)
		self.label_11.setObjectName("label_11")
		self.label_12 = QtWidgets.QLabel(self.centralwidget)
		self.label_12.setGeometry(QtCore.QRect(460, 340, 71, 16))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_12.setFont(font)
		self.label_12.setObjectName("label_12")
		self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.lineEdit.setGeometry(QtCore.QRect(340, 480, 211, 20))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.lineEdit.setFont(font)
		self.lineEdit.setReadOnly(True)
		self.lineEdit.setObjectName("lineEdit")
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		#event
		self.check_box.clicked.connect(self.check)
		self.download_now.clicked.connect(self.download_bt)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Downloader"))
		self.label.setText(_translate("MainWindow", "YOUTUBE Download"))
		self.label_2.setText(_translate("MainWindow", "Tool"))
		self.label_3.setText(_translate("MainWindow", "Link Video"))
		self.label_4.setText(_translate("MainWindow", "Make by  Hiesu"))
		self.check_box.setText(_translate("MainWindow", "CHECK"))
		self.label_5.setText(_translate("MainWindow", "Option"))
		self.label_6.setText(_translate("MainWindow", "Title"))
		self.download_now.setText(_translate("MainWindow", "DOWNLOAD NOW"))
		self.comboBox.setCurrentText(_translate("MainWindow", "video 360p"))
		self.comboBox.setItemText(0, _translate("MainWindow", "video 360p"))
		self.comboBox.setItemText(1, _translate("MainWindow", "video720p"))
		self.comboBox.setItemText(2, _translate("MainWindow", "videp 1080p"))
		self.comboBox.setItemText(3, _translate("MainWindow", "audio 128 kbps"))
		self.comboBox.setItemText(4, _translate("MainWindow", "audio 160 kbps"))
		self.label_7.setText(_translate("MainWindow", "Save in"))
		self.label_8.setText(_translate("MainWindow", "Views"))
		self.label_9.setText(_translate("MainWindow", "Thumbnail_url"))
		self.label_11.setText(_translate("MainWindow", "Example"))
		self.label_12.setText(_translate("MainWindow", "C:\\"))


	def check(self):
		url = self.get_link.text()
		try:
			title_msg = YouTube(url).title
			views_msg = str(YouTube(url).views)
			thum_img = YouTube(url).thumbnail_url
			self.title_box.setText(title_msg)
			self.view_box.setText(views_msg)
			self.thumbnail_box.setText(thum_img)
			self.label_10.setText("         Checked")

		except Exception as e:
			self.label_10.setText("ERROR:  Link Video unavailable ")
			self.title_box.setText("......")
			self.view_box.setText("......")
			self.thumbnail_box.setText("......")

	def download_bt(self):
		opti = self.comboBox.currentText()
		url = self.get_link.text()
		save_url = self.save.text()
		self.lineEdit.setText("   LOADING......")
		try:
			title_msg = YouTube(url).title
		except Exception as e:
			self.label_10.setText("ERROR:  Link Video unavailable to download ")
			self.lineEdit.setText("   Oh no :(((")
			return
		if opti == "video 360p":
			itag = "18"
			YouTube(url).streams.get_by_itag(itag).download(save_url)
			self.label_10.setText("     Finish   video 360p")
		if opti == "video 720p":
			itag = "22"
			YouTube(url).streams.get_by_itag(itag).download(save_url)
			self.label_10.setText("     Finish   video 720p")
		if opti == "video 1080p":
			itag = "137"
			YouTube(url).streams.get_by_itag(itag).download(save_url)
			self.label_10.setText("     Finish   video 1080p")
		if opti == "audio 128 kbps":
			itag = "140"
			YouTube(url).streams.get_by_itag(itag).download(save_url)
			self.label_10.setText("     Finish   audio 128 kbps")
		if opti == "audio 160 kbps":
			itag = "251"
			YouTube(url).streams.get_by_itag(itag).download(save_url)
			self.label_10.setText("     Finish   audio 160 kbps")
		mini_win = QtWidgets.QMessageBox()
		mini_win.setIcon(QtWidgets.QMessageBox.Information)
		mini_win.setText("Finish:  " + title_msg)
		if save_url =="":
			mini_win.setInformativeText("Save in : This file  ")
		else:
			mini_win.setInformativeText("Save in : " + save_url)
		mini_win.setWindowTitle("Chi phí")
		mini_win.exec_()


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
